// GENERATED by tools/codeview/gen_langmap.py -- do not edit.
// SPDX-FileCopyrightText: 2026 Pavel Stupka
// SPDX-License-Identifier: GPL-2.0-or-later
//
// Language identification tables (spec FR-005/FR-008,
// contracts/claimed-types.md). Regenerating from the pinned inputs
// reproduces this file byte for byte.

#pragma once

struct CvLanguage
{
    const char* Id;       // stable ascii id (= grammar name when one ships)
    const char* Display;  // English display name (not translated: proper names)
    const char* Grammar;  // grammar module name, or NULL = plain text (FR-003)
};

struct CvNameRule
{
    const char* Key;      // lower-case exact name / suffix / extension
    short Lang;           // index into CvLanguages
    short Rule;           // index into CvAmbiguityRules, -1 = none
};

extern const CvLanguage CvLanguages[];
extern const int CvLanguageCount;

extern const CvNameRule CvExactNames[];
extern const int CvExactNameCount;

extern const CvNameRule CvCompoundSuffixes[];
extern const int CvCompoundSuffixCount;

extern const CvNameRule CvExtensions[];
extern const int CvExtensionCount;

extern const CvNameRule CvInterpreters[];
extern const int CvInterpreterCount;

// Ambiguity rule ids, in the order of CvAmbiguityRules; intake.cpp
// implements the probe for each (spec FR-006).
enum CvAmbiguityRuleId
{
    CV_RULE_ASM_SOURCE,
    CV_RULE_CLS_FILE,
    CV_RULE_H_HEADER,
    CV_RULE_INC_INCLUDE,
    CV_RULE_M_SOURCE,
    CV_RULE_PL_SCRIPT,
    CV_RULE_R_SOURCE,
    CV_RULE_SQL_DIALECT,
    CV_RULE_T_TEST,
    CV_RULE_TS_SOURCE,
    CV_RULE_V_SOURCE,
    CV_RULE_COUNT
};

struct CvAmbiguityRule
{
    const char* Id;
    short Fallback;   // language when no probe matches
};

extern const CvAmbiguityRule CvAmbiguityRules[];

// The Viewers-list rows registered by Connect(), in DISPLAY order.
// codeview.cpp registers them in reverse (rows insert at index 0).
extern const char* const CvMaskRows[];
extern const int CvMaskRowCount;
